# Generated by Django 4.2.7 on 2023-12-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_sub_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub',
            name='validity',
            field=models.BooleanField(default=True),
        ),
    ]
