# Generated by Django 4.2.7 on 2023-12-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_sub_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
