# Generated by Django 4.2.7 on 2023-12-09 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_sub_validity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub',
            name='validity',
        ),
    ]
