# Generated by Django 5.0 on 2023-12-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_sub_validity'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub',
            name='price',
            field=models.DecimalField(decimal_places=2, default=999.9, max_digits=7),
        ),
    ]
